# Generated by Django 5.1.4 on 2024-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_chip", models.CharField(max_length=100, unique=True)),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("especie", models.CharField(max_length=100)),
                (
                    "mutacao_genetica",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("data_entrada", models.DateField(blank=True, null=True)),
                ("origem", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "parceiro_atual",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_chip_parceiro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gaiola", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Fêmea", "Fêmea")], max_length=10
                    ),
                ),
                ("mutacao", models.CharField(blank=True, max_length=100, null=True)),
                ("filhotes", models.IntegerField(default=0)),
                (
                    "investidores",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
