# Generated by Django 5.1.4 on 2024-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aves", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ave",
            old_name="investidores",
            new_name="investidor",
        ),
        migrations.CreateModel(
            name="Investidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
                ("custo_mensal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "desconto_percentual",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "aves",
                    models.ManyToManyField(related_name="investidores", to="aves.ave"),
                ),
            ],
        ),
    ]
