# Generated by Django 5.1.4 on 2024-12-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aves", "0002_rename_investidores_ave_investidor_investidor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ave",
            name="data_morte",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ave",
            name="motivo_morte",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ave",
            name="preco_compra",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ave",
            name="preco_venda",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disponível", "Disponível"),
                    ("Vendida", "Vendida"),
                    ("Morte", "Morte"),
                ],
                default="Disponível",
                max_length=10,
            ),
        ),
    ]
