# Generated by Django 5.1.4 on 2024-12-13 13:41

from django.db import migrations

def add_profiles(apps, schema_editor):
    Perfil = apps.get_model('aves', 'Perfil')
    User = apps.get_model('auth', 'User')  # Certifique-se de estar referenciando o app correto
    for user in User.objects.all():
        if not Perfil.objects.filter(user=user).exists():
            if user.is_superuser:
                perfil = 'admin'
            else:
                perfil = 'consulta'
            Perfil.objects.create(user=user, perfil=perfil)

class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0006_perfil'),  # Ajuste se necessário
    ]

    operations = [
        migrations.RunPython(add_profiles),
    ]
